RPTRST
ALLPROPS/
/

DATES
02 JAN 2003 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  229.679  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.141  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  193.555  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  113.749  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  164.587  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  119.106  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12545.460  1*  1*  /
 F-1H  WATER  OPEN  RATE  10524.790  1*  1*  /
 F-2H  WATER  OPEN  RATE   6122.108  1*  1*  /
 F-3H  WATER  OPEN  RATE   3904.430  1*  1*  /
 F-4H  WATER  OPEN  RATE   2283.729  1*  1*  /
/

DATES
12 JAN 2003 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  229.7337  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  175.4488  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  192.1757  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  115.7365  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  164.5435  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  117.5380  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7725.477  1*  1*  /
 C-2H  WATER  OPEN  RATE  12462.750  1*  1*  /
 F-1H  WATER  OPEN  RATE  10430.620  1*  1*  /
 F-2H  WATER  OPEN  RATE   6116.037  1*  1*  /
 F-3H  WATER  OPEN  RATE   3913.500  1*  1*  /
 F-4H  WATER  OPEN  RATE   2463.600  1*  1*  /
/

DATES
20 JAN 2003 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  228.927  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.422  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  225.022  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  102.557  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  163.774  /
 E-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12715.410  1*  1*  /
 F-1H  WATER  OPEN  RATE  10327.860  1*  1*  /
 F-2H  WATER  OPEN  RATE   6211.908  1*  1*  /
 F-3H  WATER  OPEN  RATE   3890.192  1*  1*  /
 F-4H  WATER  OPEN  RATE   2538.531  1*  1*  /
/

DATES
01 FEB 2003 /
/

WCONPROD
 B-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  171.363  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  220.562  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  90.1801  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  154.969  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  10799.660  1*  1*  /
 F-1H  WATER  OPEN  RATE   9431.961  1*  1*  /
 F-2H  WATER  OPEN  RATE   5504.746  1*  1*  /
 F-3H  WATER  OPEN  RATE   3512.677  1*  1*  /
 F-4H  WATER  OPEN  RATE   2147.000  1*  1*  /
/

DATES
14 FEB 2003 /
/

WCONPROD
 B-1H  OPEN  BHP  1*  1*  1*  1*  1*  228.286  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*   177.35  /
 D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*   60.466  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  155.088  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7830.924  1*  1*  /
 C-2H  WATER  OPEN  RATE  10863.580  1*  1*  /
 F-1H  WATER  OPEN  RATE  10049.200  1*  1*  /
 F-2H  WATER  OPEN  RATE   5948.473  1*  1*  /
 F-3H  WATER  OPEN  RATE   3745.073  1*  1*  /
 F-4H  WATER  OPEN  RATE   2381.260  1*  1*  /
/

DATES
01 MAR 2003 /
/

WCONPROD
 B-1H  OPEN  BHP  1*  1*  1*  1*  1*  228.47790  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  199.77690  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  206.49600  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*   66.15529  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  137.66200  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7782.110  1*  1*  /
 C-2H  WATER  OPEN  RATE  10301.600  1*  1*  /
 F-1H  WATER  OPEN  RATE  10119.800  1*  1*  /
 F-2H  WATER  OPEN  RATE   5462.798  1*  1*  /
 F-3H  WATER  OPEN  RATE   3702.200  1*  1*  /
 F-4H  WATER  OPEN  RATE   1893.198  1*  1*  /
/

DATES
06 MAR 2003 /
/

WCONPROD
 B-1H  OPEN  BHP  1*  1*  1*  1*  1*  229.19320  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  189.80200  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  207.84620  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*   75.92363  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  143.84210  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7776.206  1*  1*  /
 C-2H  WATER  OPEN  RATE  10670.000  1*  1*  /
 F-1H  WATER  OPEN  RATE  10237.000  1*  1*  /
 F-2H  WATER  OPEN  RATE   6103.000  1*  1*  /
 F-3H  WATER  OPEN  RATE   3839.000  1*  1*  /
 F-4H  WATER  OPEN  RATE   2418.000  1*  1*  /
/

DATES
07 MAR 2003 /
/

COMPDAT
 B-3H  8  40  12  12  OPEN  1*    1.879  0.216    148.474  0  1*  Y   7.444  /
 B-3H  8  40  13  13  OPEN  1*  302.749  0.216  26777.176  0  1*  Y  12.343  /
/

WCONPROD
 B-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  175.576  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*   187.06  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  201.498  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*   85.542  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  151.615  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7793.080  1*  1*  /
 C-2H  WATER  OPEN  RATE  10314.840  1*  1*  /
 F-1H  WATER  OPEN  RATE   9837.481  1*  1*  /
 F-2H  WATER  OPEN  RATE   5947.878  1*  1*  /
 F-3H  WATER  OPEN  RATE   2535.840  1*  1*  /
 F-4H  WATER  OPEN  RATE   2498.638  1*  1*  /
/

DATES
01 APR 2003 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  179.085  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  187.781  /
 D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  131.569  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*    196.8  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7803.189  1*  1*  /
 C-2H  WATER  OPEN  RATE  10846.560  1*  1*  /
 F-1H  WATER  OPEN  RATE   9672.235  1*  1*  /
 F-2H  WATER  OPEN  RATE   5770.398  1*  1*  /
 F-3H  WATER  OPEN  RATE   3383.467  1*  1*  /
 F-4H  WATER  OPEN  RATE   2344.065  1*  1*  /
/

DATES
01 MAY 2003 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  178.4163  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  183.9768  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  199.7584  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  102.0948  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  166.8527  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE  7818.780  1*  1*  /
 C-2H  WATER  OPEN  RATE  8288.224  1*  1*  /
 C-4H  WATER  OPEN  RATE    36.581  1*  1*  /
 F-1H  WATER  OPEN  RATE  7074.000  1*  1*  /
 F-2H  WATER  OPEN  RATE  3689.095  1*  1*  /
 F-3H  WATER  OPEN  RATE  2346.355  1*  1*  /
 F-4H  WATER  OPEN  RATE  1529.677  1*  1*  /
/

DATES
01 JUN 2003 /
/

WCONPROD
 C-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  170.948  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.945  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*    192.7  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  127.755  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  162.911  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7820.437  1*  1*  /
 C-2H  WATER  OPEN  RATE  10935.000  1*  1*  /
 F-1H  WATER  OPEN  RATE  11088.500  1*  1*  /
 F-2H  WATER  OPEN  RATE   6565.000  1*  1*  /
 F-3H  WATER  OPEN  RATE   4019.000  1*  1*  /
 F-4H  WATER  OPEN  RATE   2532.500  1*  1*  /
/

DATES
03 JUN 2003 /
/

COMPDAT
 D-4AH  17  75  2  2  OPEN  1*    9.931  0.216    734.755  0  1*  Y  5.687  /
 D-4AH  17  76  2  2  OPEN  1*   27.106  0.216   2004.161  0  1*  Y  5.673  /
 D-4AH  18  76  2  2  OPEN  1*   11.598  0.216    856.594  0  1*  Y  5.648  /
 D-4AH  18  77  2  2  OPEN  1*   15.852  0.216   1168.451  0  1*  Y  5.604  /
 D-4AH  18  79  1  1  OPEN  1*  110.061  0.216   9263.623  0  1*  Y  9.814  /
 D-4AH  18  80  1  1  OPEN  1*  131.888  0.216  11040.175  0  1*  Y  9.576  /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  176.9030  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.1815  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  196.6963  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  154.6898  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  172.4001  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7819.729  1*  1*  /
 C-2H  WATER  OPEN  RATE  10361.030  1*  1*  /
 F-1H  WATER  OPEN  RATE   6647.321  1*  1*  /
 F-2H  WATER  OPEN  RATE   6412.750  1*  1*  /
 F-3H  WATER  OPEN  RATE   3964.250  1*  1*  /
 F-4H  WATER  OPEN  RATE   2990.284  1*  1*  /
/

DATES
01 JUL 2003 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  207.6437  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  181.6562  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  201.0453  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  166.0157  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  186.8834  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   3713.000  1*  1*  /
 C-2H  WATER  OPEN  RATE  15661.880  1*  1*  /
 F-1H  WATER  OPEN  RATE  11314.870  1*  1*  /
 F-2H  WATER  OPEN  RATE   6735.776  1*  1*  /
 F-3H  WATER  OPEN  RATE   4133.333  1*  1*  /
 F-4H  WATER  OPEN  RATE   2619.666  1*  1*  /
/

DATES
10 JUL 2003 /
/

WCONPROD
 C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  206.944  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  168.286  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  196.562  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  145.885  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*   159.99  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  11001.040  1*  1*  /
 C-3H  WATER  OPEN  RATE  10376.220  1*  1*  /
 F-1H  WATER  OPEN  RATE  11282.720  1*  1*  /
 F-2H  WATER  OPEN  RATE   7109.727  1*  1*  /
 F-3H  WATER  OPEN  RATE   4226.455  1*  1*  /
 F-4H  WATER  OPEN  RATE   3139.955  1*  1*  /
/

DATES
01 AUG 2003 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  202.4049  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  166.9830  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  205.1649  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  251.2980  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  156.7960  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  158.9680  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  171.3119  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  10745.880  1*  1*  /
 C-3H  WATER  OPEN  RATE  10165.330  1*  1*  /
 F-1H  WATER  OPEN  RATE  11091.440  1*  1*  /
 F-2H  WATER  OPEN  RATE   7034.109  1*  1*  /
 F-3H  WATER  OPEN  RATE   4183.778  1*  1*  /
 F-4H  WATER  OPEN  RATE   3157.554  1*  1*  /
/

DATES
10 AUG 2003 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  199.8553  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.5467  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  197.7202  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  251.3020  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  162.0392  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.3829  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  169.3231  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  16307.5  1*  1*  /
 C-3H  WATER  OPEN  RATE   5052.0  1*  1*  /
 F-1H  WATER  OPEN  RATE  11001.5  1*  1*  /
 F-2H  WATER  OPEN  RATE   6893.5  1*  1*  /
 F-3H  WATER  OPEN  RATE   4187.0  1*  1*  /
 F-4H  WATER  OPEN  RATE   3021.0  1*  1*  /
/

DATES
12 AUG 2003 /
/

WCONPROD
  C-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*   211.55  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  180.105  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  194.889  /
 D-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  169.601  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.088  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*   151.67  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7734.905  1*  1*  /
 C-2H  WATER  OPEN  RATE  10711.340  1*  1*  /
 F-1H  WATER  OPEN  RATE  10673.200  1*  1*  /
 F-2H  WATER  OPEN  RATE   6723.950  1*  1*  /
 F-3H  WATER  OPEN  RATE   4040.800  1*  1*  /
 F-4H  WATER  OPEN  RATE   3002.948  1*  1*  /
/

DATES
01 SEP 2003 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  212.246  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  170.255  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  186.437  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  142.667  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  167.727  /
 E-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7718.027  1*  1*  /
 C-2H  WATER  OPEN  RATE   8643.400  1*  1*  /
 F-1H  WATER  OPEN  RATE  10698.400  1*  1*  /
 F-2H  WATER  OPEN  RATE   6471.500  1*  1*  /
 F-3H  WATER  OPEN  RATE   3949.500  1*  1*  /
 F-4H  WATER  OPEN  RATE   2587.398  1*  1*  /
/

DATES
02 SEP 2003 /
/

WCONPROD
 C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  211.777  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  161.167  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  182.479  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*   158.08  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  172.853  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12930.200  1*  1*  /
 F-1H  WATER  OPEN  RATE  10948.110  1*  1*  /
 F-2H  WATER  OPEN  RATE   6806.336  1*  1*  /
 F-3H  WATER  OPEN  RATE   4065.112  1*  1*  /
 F-4H  WATER  OPEN  RATE   2908.112  1*  1*  /
/

DATES
10 SEP 2003 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  214.3659  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  160.7039  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  179.8229  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  151.8320  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  172.8569  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12811.20  1*  1*  /
 F-1H  WATER  OPEN  RATE  10776.40  1*  1*  /
 F-2H  WATER  OPEN  RATE   6708.75  1*  1*  /
 F-3H  WATER  OPEN  RATE   4016.35  1*  1*  /
 F-4H  WATER  OPEN  RATE   2884.00  1*  1*  /
/

DATES
12 SEP 2003 /
/

COMPDAT
 B-1H  15  37  7  7  OPEN  1*  32.414  0.216  2564.617  0  1*  Y  7.489  /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  213.7404  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  167.1566  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.6468  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  149.3134  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.2239  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12756.800  1*  1*  /
 F-1H  WATER  OPEN  RATE  10659.300  1*  1*  /
 F-2H  WATER  OPEN  RATE   6599.398  1*  1*  /
 F-3H  WATER  OPEN  RATE   3955.500  1*  1*  /
 F-4H  WATER  OPEN  RATE   2792.600  1*  1*  /
/

DATES
13 SEP 2003 /
/

COMPDAT
 B-1H  15  36  5  5  OPEN  1*  51.932  0.216  4231.565  0  1*  Y  8.499  /
 B-1H  15  37  7  7  OPEN  1*  32.414  0.216  2564.617  0  1*  Y  7.489  /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  211.9880  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  164.7651  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  199.1573  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  147.6965  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  169.9608  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  12859.750  1*  1*  /
 F-1H  WATER  OPEN  RATE  10659.800  1*  1*  /
 F-2H  WATER  OPEN  RATE   6622.367  1*  1*  /
 F-3H  WATER  OPEN  RATE   3978.467  1*  1*  /
 F-4H  WATER  OPEN  RATE   2858.698  1*  1*  /
/

DATES
16 SEP 2003 /
/

COMPDAT
 B-1H  15  36  5  5  OPEN  1*  51.932  0.216  4231.565  0  1*  Y  8.499  /
 B-1H  15  37  7  7  OPEN  1*  32.414  0.216  2564.617  0  1*  Y  7.489  /
/

WCONPROD
 B-1H  OPEN  BHP  1*  1*  1*  1*  1*  165.3300  /
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  219.4810  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  157.9310  /
 D-2H  OPEN  BHP  1*  1*  1*  1*  1*  209.6380  /
 E-1H  OPEN  BHP  1*  1*  1*  1*  1*  179.3399  /
 E-2H  OPEN  BHP  1*  1*  1*  1*  1*  196.7619  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  11062.460  1*  1*  /
 C-4H  WATER  OPEN  RATE      8.467  1*  1*  /
 F-1H  WATER  OPEN  RATE   8998.580  1*  1*  /
 F-2H  WATER  OPEN  RATE   5574.445  1*  1*  /
 F-3H  WATER  OPEN  RATE   6400.613  1*  1*  /
 F-4H  WATER  OPEN  RATE   2329.060  1*  1*  /
/

DATES
01 OCT 2003 /
/

WCONPROD
  C-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  136.723  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  211.092  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  148.163  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  194.557  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  252.268  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  181.786  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*   198.25  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  122.936  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7708.618  1*  1*  /
 C-2H  WATER  OPEN  RATE  11344.040  1*  1*  /
 F-1H  WATER  OPEN  RATE   9697.414  1*  1*  /
 F-2H  WATER  OPEN  RATE   7019.775  1*  1*  /
 F-3H  WATER  OPEN  RATE   4204.877  1*  1*  /
 F-4H  WATER  OPEN  RATE   3249.791  1*  1*  /
/

DATES
23 OCT 2003 /
/

COMPDAT
 D-1CH  24  31  5  5  OPEN  1*  19.917  0.216  1441.266  0  1*  Y  5.215  /
 D-1CH  24  30  5  5  OPEN  1*  14.238  0.216  1021.922  0  1*  Y  5.052  /
 D-1CH  23  30  7  7  OPEN  1*  16.976  0.216  1219.509  0  1*  Y  5.069  /
 D-1CH  23  29  7  7  OPEN  1*  11.916  0.216   861.151  0  1*  Y  5.188  /
 D-1CH  23  29  8  8  OPEN  1*  73.196  0.216  5215.255  0  1*  Y  4.912  /
 D-1CH  23  28  8  8  OPEN  1*  68.299  0.216  4862.940  0  1*  Y  4.899  /
 D-1CH  23  27  8  8  OPEN  1*  66.326  0.216  4732.528  0  1*  Y  4.939  /
 D-1CH  23  26  8  8  OPEN  1*   7.330  0.216   518.770  0  1*  Y  4.788  /
 D-1CH  22  26  8  8  OPEN  1*  10.485  0.216   765.307  0  1*  Y  5.391  /
 D-1CH  22  26  7  7  OPEN  1*  27.436  0.216  2000.367  0  1*  Y  5.369  /
 D-1CH  22  25  7  7  OPEN  1*  50.384  0.216  3765.310  0  1*  Y  5.920  /
 D-1CH  22  24  7  7  OPEN  1*  50.321  0.216  3774.040  0  1*  Y  6.005  /
 D-1CH  22  23  7  7  OPEN  1*  40.979  0.216  3072.773  0  1*  Y  6.000  /
 D-1CH  21  23  7  7  OPEN  1*   3.734  0.216   279.692  0  1*  Y  5.976  /
 D-1CH  21  22  7  7  OPEN  1*  41.777  0.216  3146.139  0  1*  Y  6.105  /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  101.3983  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  207.1029  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  147.5796  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  187.0263  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  248.9040  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  185.7359  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  194.8217  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  117.0891  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7684.088  1*  1*  /
 C-2H  WATER  OPEN  RATE  10899.210  1*  1*  /
 F-1H  WATER  OPEN  RATE   9904.589  1*  1*  /
 F-2H  WATER  OPEN  RATE   6765.500  1*  1*  /
 F-3H  WATER  OPEN  RATE   4257.200  1*  1*  /
 F-4H  WATER  OPEN  RATE   3307.354  1*  1*  /
/

DATES
01 NOV 2003 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  97.4512  /
  B-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  142.227  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  209.667  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*   195.13  /
 D-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*    186.8  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  195.335  /
 E-4AH  OPEN  BHP  1*  1*  1*  1*  1*  144.263  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE  7683.921  1*  1*  /
 C-2H  WATER  OPEN  RATE  9962.377  1*  1*  /
 F-1H  WATER  OPEN  RATE  7707.429  1*  1*  /
 F-2H  WATER  OPEN  RATE  6553.429  1*  1*  /
 F-3H  WATER  OPEN  RATE  4038.059  1*  1*  /
 F-4H  WATER  OPEN  RATE  3244.812  1*  1*  /
/

DATES
18 NOV 2003 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  91.3996  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  131.974  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  194.731  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  187.469  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  165.168  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  171.775  /
 E-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7665.042  1*  1*  /
 C-2H  WATER  OPEN  RATE  10775.100  1*  1*  /
 F-1H  WATER  OPEN  RATE   6556.046  1*  1*  /
 F-2H  WATER  OPEN  RATE   7026.029  1*  1*  /
 F-3H  WATER  OPEN  RATE   4398.031  1*  1*  /
 F-4H  WATER  OPEN  RATE   3469.003  1*  1*  /
/

DATES
01 DEC 2003 /
/

WCONPROD
  F-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  95.8343  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  131.409  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  183.641  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  196.887  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  153.031  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.311  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7651.542  1*  1*  /
 C-2H  WATER  OPEN  RATE  11004.200  1*  1*  /
 F-2H  WATER  OPEN  RATE   7007.891  1*  1*  /
 F-3H  WATER  OPEN  RATE   5469.886  1*  1*  /
 F-4H  WATER  OPEN  RATE   3247.024  1*  1*  /
/

DATES
08 DEC 2003 /
/

COMPDAT
 C-4AH  29  51   1   1  OPEN  1*  23.332  0.216  2235.565  0  1*  Z  18.317  /
 C-4AH  29  52   5   5  OPEN  1*   7.123  0.216   676.723  0  1*  Z  17.544  /
 C-4AH  29  52   8   8  OPEN  1*   8.905  0.216   851.926  0  1*  Z  18.173  /
 C-4AH  29  51   2   2  OPEN  1*   6.052  0.216   575.515  0  1*  Z  17.628  /
 C-4AH  29  51   3   3  OPEN  1*  13.822  0.216  1229.859  0  1*  Z  12.701  /
 C-4AH  29  52   6   6  OPEN  1*   7.162  0.216   682.067  0  1*  Z  17.756  /
 C-4AH  29  52   7   7  OPEN  1*   8.904  0.216   851.095  0  1*  Z  18.096  /
 C-4AH  29  52   3   3  OPEN  1*   2.148  0.216   192.252  0  1*  Z  13.066  /
 C-4AH  29  52   9   9  OPEN  1*   0.322  0.216    30.878  0  1*  Z  18.377  /
 C-4AH  29  52  10  10  OPEN  1*  24.591  0.216  2370.923  0  1*  Z  18.915  /
 C-4AH  29  52  13  13  OPEN  1*  68.015  0.216  6527.337  0  1*  Z  18.469  /
 C-4AH  29  52  14  14  OPEN  1*   6.636  0.216   637.537  0  1*  Z  18.567  /
 C-4AH  29  52  15  15  OPEN  1*   1.969  0.216   189.710  0  1*  Z  18.864  /
 C-4AH  29  52  11  11  OPEN  1*   9.994  0.216   961.288  0  1*  Z  18.683  /
 C-4AH  29  52  12  12  OPEN  1*   1.631  0.216   157.349  0  1*  Z  18.968  /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  82.7362  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*   123.63  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  177.219  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*   163.25  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.624  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7649.539  1*  1*  /
 C-2H  WATER  OPEN  RATE  10871.300  1*  1*  /
 F-2H  WATER  OPEN  RATE   6991.604  1*  1*  /
 F-3H  WATER  OPEN  RATE   5624.200  1*  1*  /
 F-4H  WATER  OPEN  RATE   2976.300  1*  1*  /
/

DATES
09 DEC 2003 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*   95.25573  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  137.60170  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  186.22540  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  197.04220  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  188.11660  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  198.86210  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7632.346  1*  1*  /
 C-2H  WATER  OPEN  RATE  10597.030  1*  1*  /
 F-1H  WATER  OPEN  RATE   7923.356  1*  1*  /
 F-2H  WATER  OPEN  RATE   6928.935  1*  1*  /
 F-3H  WATER  OPEN  RATE   4292.222  1*  1*  /
 F-4H  WATER  OPEN  RATE   2322.289  1*  1*  /
/

DATES
18 DEC 2003 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  91.2852  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  114.277  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  174.026  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  189.868  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  160.306  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.158  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE  11870.570  1*  1*  /
 F-1H  WATER  OPEN  RATE  11121.010  1*  1*  /
 F-2H  WATER  OPEN  RATE   6886.770  1*  1*  /
 F-3H  WATER  OPEN  RATE   4255.257  1*  1*  /
 F-4H  WATER  OPEN  RATE   1908.641  1*  1*  /
/

DATES
01 JAN 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*   90.25689  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  106.40300  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  170.56590  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  183.33290  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  158.64790  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*  173.42100  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE   9278.033  1*  1*  /
 F-1H  WATER  OPEN  RATE  11094.860  1*  1*  /
 F-2H  WATER  OPEN  RATE   6879.755  1*  1*  /
 F-3H  WATER  OPEN  RATE   4291.683  1*  1*  /
 F-4H  WATER  OPEN  RATE   1804.015  1*  1*  /
/

DATES
19 JAN 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  105.282  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  127.644  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  182.154  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  164.396  /
  E-2H  OPEN  BHP  1*  1*  1*  1*  1*   198.43  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE   1419.900  1*  1*  /
 C-3H  WATER  OPEN  RATE    541.200  1*  1*  /
 F-1H  WATER  OPEN  RATE  10921.100  1*  1*  /
 F-2H  WATER  OPEN  RATE   6846.500  1*  1*  /
 F-3H  WATER  OPEN  RATE   4394.700  1*  1*  /
 F-4H  WATER  OPEN  RATE   1990.198  1*  1*  /
/

DATES
20 JAN 2004 /
/

COMPDAT
 C-4AH  29  52   6   6  OPEN  1*   1.703  0.216   162.180  0  1*  Z  17.743  /
 C-4AH  29  52   7   7  OPEN  1*   8.904  0.216   851.095  0  1*  Z  18.096  /
 C-4AH  29  52   8   8  OPEN  1*   8.905  0.216   851.926  0  1*  Z  18.173  /
 C-4AH  29  52   9   9  OPEN  1*   0.322  0.216    30.878  0  1*  Z  18.377  /
 C-4AH  29  52   5   5  OPEN  1*   7.123  0.216   676.723  0  1*  Z  17.544  /
 C-4AH  29  52  10  10  OPEN  1*  20.273  0.216  1954.730  0  1*  Z  18.919  /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  79.1456  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  100.454  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  166.738  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.198  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE   5827.083  1*  1*  /
  C-3H  WATER  OPEN  RATE   2321.425  1*  1*  /
 C-4AH  WATER  OPEN  RATE   6034.065  1*  1*  /
  F-1H  WATER  OPEN  RATE  10278.500  1*  1*  /
  F-2H  WATER  OPEN  RATE   6175.083  1*  1*  /
  F-3H  WATER  OPEN  RATE   4150.550  1*  1*  /
  F-4H  WATER  OPEN  RATE   1840.448  1*  1*  /
/

DATES
01 FEB 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*   80.71111  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  184.77130  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*   76.61833  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  149.19430  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  179.98800  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  187.40870  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE   7776.334  1*  1*  /
  C-3H  WATER  OPEN  RATE   8913.754  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5314.407  1*  1*  /
  F-1H  WATER  OPEN  RATE  10371.070  1*  1*  /
  F-2H  WATER  OPEN  RATE   6764.757  1*  1*  /
  F-3H  WATER  OPEN  RATE   4134.631  1*  1*  /
  F-4H  WATER  OPEN  RATE   1829.520  1*  1*  /
/

DATES
01 MAR 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  89.7039  /
  B-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  68.1908  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  134.295  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  162.971  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  191.831  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE   9665.524  1*  1*  /
  C-3H  WATER  OPEN  RATE   9045.154  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5053.642  1*  1*  /
  F-1H  WATER  OPEN  RATE  10216.320  1*  1*  /
  F-2H  WATER  OPEN  RATE   6710.719  1*  1*  /
  F-3H  WATER  OPEN  RATE   4055.310  1*  1*  /
  F-4H  WATER  OPEN  RATE   1829.505  1*  1*  /
/

DATES
01 APR 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  92.0947  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  173.666  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*   138.66  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  118.452  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  155.746  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE   9612.317  1*  1*  /
  C-3H  WATER  OPEN  RATE   8789.753  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5301.381  1*  1*  /
  F-1H  WATER  OPEN  RATE  10136.570  1*  1*  /
  F-2H  WATER  OPEN  RATE   6610.175  1*  1*  /
  F-3H  WATER  OPEN  RATE   4121.383  1*  1*  /
  F-4H  WATER  OPEN  RATE   1849.790  1*  1*  /
/

DATES
01 MAY 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  115.8289  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  166.8029  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  131.1519  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  113.7379  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  156.3424  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE   9836.877  1*  1*  /
  C-3H  WATER  OPEN  RATE   9244.531  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4619.974  1*  1*  /
  F-1H  WATER  OPEN  RATE  10009.540  1*  1*  /
  F-2H  WATER  OPEN  RATE   6511.381  1*  1*  /
  F-3H  WATER  OPEN  RATE   4121.700  1*  1*  /
  F-4H  WATER  OPEN  RATE   1837.473  1*  1*  /
/

DATES
01 JUN 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*   28.62619  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  167.55360  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  158.15220  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  125.83270  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  167.55180  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  10844.300  1*  1*  /
  C-3H  WATER  OPEN  RATE   4330.060  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5252.028  1*  1*  /
  F-1H  WATER  OPEN  RATE   9981.055  1*  1*  /
  F-2H  WATER  OPEN  RATE   6464.441  1*  1*  /
  F-3H  WATER  OPEN  RATE   4153.247  1*  1*  /
  F-4H  WATER  OPEN  RATE   1855.511  1*  1*  /
/

DATES
01 JUL 2004 /
/

COMPDAT
 B-4DH  16  25  8  8  OPEN  1*   15.881  0.216  1261.727  0  1*  X  7.622  /
 B-4DH  16  25  9  9  OPEN  1*   87.421  0.216  6660.474  0  1*  X  6.400  /
 B-4DH  17  25  9  9  OPEN  1*  107.811  0.216  8028.364  0  1*  X  5.836  /
 B-4DH  17  24  9  9  OPEN  1*   18.763  0.216  1409.099  0  1*  X  6.037  /
 B-4DH  17  24  8  8  OPEN  1*    2.488  0.216   192.408  0  1*  X  6.810  /
 B-4DH  18  24  8  8  OPEN  1*   67.237  0.216  5205.294  0  1*  X  6.836  /
 B-4DH  18  24  7  7  OPEN  1*    5.564  0.216   436.127  0  1*  X  7.198  /
 B-4DH  19  24  7  7  OPEN  1*   27.154  0.216  2134.574  0  1*  X  7.287  /
 B-4DH  19  24  6  6  OPEN  1*   14.478  0.216  1144.535  0  1*  X  7.461  /
 B-4DH  19  24  5  5  OPEN  1*   18.023  0.216  1421.043  0  1*  X  7.379  /
 B-4DH  20  24  5  5  OPEN  1*   11.634  0.216   900.185  0  1*  X  6.820  /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*   60.8671  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  166.7131  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  159.6015  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  123.0283  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  164.0579  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  226.8694  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  9845.950  1*  1*  /
  C-3H  WATER  OPEN  RATE  8764.450  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4438.798  1*  1*  /
  F-1H  WATER  OPEN  RATE  9493.050  1*  1*  /
  F-2H  WATER  OPEN  RATE  6462.665  1*  1*  /
  F-3H  WATER  OPEN  RATE  4233.100  1*  1*  /
  F-4H  WATER  OPEN  RATE  1919.198  1*  1*  /
/

DATES
03 JUL 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  137.878  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  170.813  /
  B-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  132.881  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*   171.21  /
 D-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  10257.030  1*  1*  /
  C-3H  WATER  OPEN  RATE   7697.327  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4377.682  1*  1*  /
  F-1H  WATER  OPEN  RATE   6645.145  1*  1*  /
  F-2H  WATER  OPEN  RATE   6463.309  1*  1*  /
  F-3H  WATER  OPEN  RATE   4184.450  1*  1*  /
  F-4H  WATER  OPEN  RATE   2011.921  1*  1*  /
/

DATES
25 JUL 2004 /
/

WCONPROD
  C-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*    1.013  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  172.526  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  139.707  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.847  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  11255.950  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4510.398  1*  1*  /
  F-1H  WATER  OPEN  RATE   9118.486  1*  1*  /
  F-2H  WATER  OPEN  RATE   5323.686  1*  1*  /
  F-3H  WATER  OPEN  RATE   3471.614  1*  1*  /
  F-4H  WATER  OPEN  RATE   1412.857  1*  1*  /
/

DATES
01 AUG 2004 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  17.979  /
  B-3H  STOP  BHP  1*  1*  1*  1*  1*      1*  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  147.85  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  175.58  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  11915.700  1*  1*  /
 C-4AH  WATER  OPEN  RATE   6127.084  1*  1*  /
  F-1H  WATER  OPEN  RATE   9612.871  1*  1*  /
  F-2H  WATER  OPEN  RATE   6537.579  1*  1*  /
  F-3H  WATER  OPEN  RATE   4051.386  1*  1*  /
  F-4H  WATER  OPEN  RATE   1801.270  1*  1*  /
/

DATES
15 AUG 2004 /
/

WCONPROD
  B-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  151.181  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  169.076  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  12552.090  1*  1*  /
 C-4AH  WATER  OPEN  RATE   6501.700  1*  1*  /
  F-1H  WATER  OPEN  RATE   9947.701  1*  1*  /
  F-2H  WATER  OPEN  RATE   6678.582  1*  1*  /
  F-3H  WATER  OPEN  RATE   4265.800  1*  1*  /
  F-4H  WATER  OPEN  RATE   1897.000  1*  1*  /
/

DATES
16 AUG 2004 /
/

WCONPROD
 D-1CH  STOP  BHP  1*  1*  1*  1*  1*  1*  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*  1*  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  4587.9750  1*  1*  /
 C-4AH  WATER  OPEN  RATE  2493.6000  1*  1*  /
  F-1H  WATER  OPEN  RATE  3774.3310  1*  1*  /
  F-2H  WATER  OPEN  RATE  2493.4170  1*  1*  /
  F-3H  WATER  OPEN  RATE  1578.4190  1*  1*  /
  F-4H  WATER  OPEN  RATE   709.7188  1*  1*  /
/

DATES
01 SEP 2004 /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  5998.795  1*  1*  /
 C-4AH  WATER  OPEN  RATE  2653.247  1*  1*  /
  F-1H  WATER  OPEN  RATE  5282.784  1*  1*  /
  F-2H  WATER  OPEN  RATE  3354.114  1*  1*  /
  F-3H  WATER  OPEN  RATE  1986.711  1*  1*  /
  F-4H  WATER  OPEN  RATE   859.489  1*  1*  /
/

DATES
20 SEP 2004 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  124.230  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  165.488  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  169.968  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   8624.897  1*  1*  /
  C-2H  WATER  OPEN  RATE   9970.209  1*  1*  /
 C-4AH  WATER  OPEN  RATE   2777.480  1*  1*  /
  F-1H  WATER  OPEN  RATE  10519.790  1*  1*  /
  F-2H  WATER  OPEN  RATE   5972.671  1*  1*  /
  F-3H  WATER  OPEN  RATE   3968.527  1*  1*  /
  F-4H  WATER  OPEN  RATE   1761.055  1*  1*  /
/

DATES
01 OCT 2004 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  125.7804  /
 B-4DH  OPEN  BHP  1*  1*  1*  1*  1*  168.6159  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  151.4662  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.3695  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7685.562  1*  1*  /
  C-2H  WATER  OPEN  RATE  8338.861  1*  1*  /
 C-4AH  WATER  OPEN  RATE  2811.623  1*  1*  /
  F-1H  WATER  OPEN  RATE  8211.381  1*  1*  /
  F-2H  WATER  OPEN  RATE  5744.242  1*  1*  /
  F-3H  WATER  OPEN  RATE  3518.735  1*  1*  /
  F-4H  WATER  OPEN  RATE  1534.458  1*  1*  /
/

DATES
01 NOV 2004 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  140.357  /
 B-4DH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  148.636  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7570.604  1*  1*  /
  C-2H  WATER  OPEN  RATE  8911.793  1*  1*  /
 C-4AH  WATER  OPEN  RATE  2841.075  1*  1*  /
  F-1H  WATER  OPEN  RATE  9539.010  1*  1*  /
  F-2H  WATER  OPEN  RATE  5406.910  1*  1*  /
  F-3H  WATER  OPEN  RATE  3478.887  1*  1*  /
  F-4H  WATER  OPEN  RATE  1395.411  1*  1*  /
/

DATES
01 DEC 2004 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  141.0014  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  138.6098  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7460.976  1*  1*  /
  C-2H  WATER  OPEN  RATE   9064.143  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4303.279  1*  1*  /
  F-1H  WATER  OPEN  RATE  10036.980  1*  1*  /
  F-2H  WATER  OPEN  RATE   5846.826  1*  1*  /
  F-3H  WATER  OPEN  RATE   3648.290  1*  1*  /
  F-4H  WATER  OPEN  RATE   1555.875  1*  1*  /
/

DATES
01 JAN 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  148.336  /
 D-1CH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7426.158  1*  1*  /
  C-2H  WATER  OPEN  RATE   9943.573  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4097.771  1*  1*  /
  F-1H  WATER  OPEN  RATE  10465.230  1*  1*  /
  F-2H  WATER  OPEN  RATE   6540.827  1*  1*  /
  F-3H  WATER  OPEN  RATE   3905.445  1*  1*  /
  F-4H  WATER  OPEN  RATE   1733.443  1*  1*  /
/

DATES
12 JAN 2005 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  158.8979  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7390.951  1*  1*  /
  C-2H  WATER  OPEN  RATE  9776.031  1*  1*  /
 C-4AH  WATER  OPEN  RATE  3550.241  1*  1*  /
  F-1H  WATER  OPEN  RATE  9892.195  1*  1*  /
  F-2H  WATER  OPEN  RATE  6018.919  1*  1*  /
  F-3H  WATER  OPEN  RATE  3680.350  1*  1*  /
  F-4H  WATER  OPEN  RATE  1580.493  1*  1*  /
/

DATES
26 JAN 2005 /
/

WCONPROD
 C-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  176.587  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  169.556  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  217.262  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  181.771  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7387.477  1*  1*  /
 C-2H  WATER  OPEN  RATE  10350.340  1*  1*  /
 C-3H  WATER  OPEN  RATE   3669.933  1*  1*  /
 F-1H  WATER  OPEN  RATE   9734.715  1*  1*  /
 F-2H  WATER  OPEN  RATE   6024.065  1*  1*  /
 F-3H  WATER  OPEN  RATE   3576.383  1*  1*  /
 F-4H  WATER  OPEN  RATE   1627.615  1*  1*  /
/

DATES
01 FEB 2005 /
/

WCONPROD
  B-1H  OPEN  BHP  1*  1*  1*  1*  1*  173.1311  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  154.1318  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  211.5249  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  185.4463  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7361.022  1*  1*  /
 C-2H  WATER  OPEN  RATE   9860.139  1*  1*  /
 C-3H  WATER  OPEN  RATE   3835.354  1*  1*  /
 F-1H  WATER  OPEN  RATE  10187.590  1*  1*  /
 F-2H  WATER  OPEN  RATE   6411.386  1*  1*  /
 F-3H  WATER  OPEN  RATE   3857.336  1*  1*  /
 F-4H  WATER  OPEN  RATE   1708.234  1*  1*  /
/

DATES
01 MAR 2005 /
/

WCONPROD
  B-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  151.544  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*   212.68  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7338.341  1*  1*  /
 C-2H  WATER  OPEN  RATE   9123.164  1*  1*  /
 C-3H  WATER  OPEN  RATE   3265.482  1*  1*  /
 F-1H  WATER  OPEN  RATE  10101.820  1*  1*  /
 F-2H  WATER  OPEN  RATE   6370.700  1*  1*  /
 F-3H  WATER  OPEN  RATE   3765.232  1*  1*  /
 F-4H  WATER  OPEN  RATE   1707.000  1*  1*  /
/

DATES
23 MAR 2005 /
/

COMPDAT
 E-3BH  15  74   1   1  OPEN  1*   72.602  0.216   6469.182  0  1*  Y  12.786  /
 E-3BH  15  74   2   2  OPEN  1*    9.222  0.216    798.702  0  1*  Y  11.183  /
 E-3BH  15  73   2   2  OPEN  1*   58.179  0.216   5009.146  0  1*  Y  10.884  /
 E-3BH  15  73   3   3  OPEN  1*    6.202  0.216    540.747  0  1*  Y  11.541  /
 E-3BH  14  72   5   5  OPEN  1*    5.253  0.216    454.866  0  1*  Y  11.176  /
 E-3BH  14  72   6   6  OPEN  1*    5.052  0.216    442.108  0  1*  Y  11.743  /
 E-3BH  14  72   7   7  OPEN  1*    7.318  0.216    642.427  0  1*  Y  11.911  /
 E-3BH  14  72   8   8  OPEN  1*    7.048  0.216    623.356  0  1*  Y  12.338  /
 E-3BH  14  72   9   9  OPEN  1*    3.056  0.216    273.526  0  1*  Y  13.062  /
 E-3BH  14  72  10  10  OPEN  1*  104.732  0.216   9415.676  0  1*  Y  13.344  /
 E-3BH  14  71  10  10  OPEN  1*   33.740  0.216   3071.740  0  1*  Y  14.183  /
 E-3BH  14  71  11  11  OPEN  1*    5.907  0.216    533.345  0  1*  Y  13.628  /
 E-3BH  14  71  12  12  OPEN  1*    1.423  0.216    128.359  0  1*  Y  13.547  /
 E-3BH  14  71  13  13  OPEN  1*  256.563  0.216  23744.156  0  1*  Y  15.375  /
 E-3BH  14  71  14  14  OPEN  1*  131.335  0.216  12193.771  0  1*  Y  15.622  /
 E-3BH  14  71  15  15  OPEN  1*   19.581  0.216   1820.504  0  1*  Y  15.731  /
 E-3BH  14  70  15  15  OPEN  1*    1.593  0.216    148.353  0  1*  Y  15.848  /
 E-3BH  13  70  15  15  OPEN  1*    9.602  0.216    896.528  0  1*  Y  16.066  /
 E-3BH  13  70  16  16  OPEN  1*  140.456  0.216  13076.664  0  1*  Y  15.839  /
 E-3BH  13  70  17  17  OPEN  1*   29.301  0.216   2742.680  0  1*  Y  16.271  /
 E-3BH  13  70  18  18  OPEN  1*    3.458  0.216    332.166  0  1*  Y  18.562  /
 E-3BH  13  70  19  19  OPEN  1*    0.184  0.216     17.651  0  1*  Z  18.501  /
 E-3BH  13  70  20  20  OPEN  1*   57.160  0.216   5606.009  0  1*  Z  20.676  /
 E-3BH  13  70  21  21  OPEN  1*   37.673  0.216   3608.930  0  1*  Z  18.299  /
 E-3BH  13  69  21  21  OPEN  1*    7.997  0.216    767.171  0  1*  Y  18.429  /
 E-3BH  13  69  22  22  OPEN  1*  384.977  0.216  37246.680  0  1*  Z  19.259  /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  149.4660  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  212.8645  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  193.7359  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7337.362  1*  1*  /
 C-2H  WATER  OPEN  RATE  10222.500  1*  1*  /
 C-3H  WATER  OPEN  RATE   3970.600  1*  1*  /
 F-1H  WATER  OPEN  RATE  10307.790  1*  1*  /
 F-2H  WATER  OPEN  RATE   6570.898  1*  1*  /
 F-3H  WATER  OPEN  RATE   3923.700  1*  1*  /
 F-4H  WATER  OPEN  RATE   1773.000  1*  1*  /
/

DATES
24 MAR 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  145.359  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  212.706  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7326.868  1*  1*  /
 C-2H  WATER  OPEN  RATE  10120.830  1*  1*  /
 C-3H  WATER  OPEN  RATE   3967.100  1*  1*  /
 F-1H  WATER  OPEN  RATE  10272.930  1*  1*  /
 F-2H  WATER  OPEN  RATE   6553.187  1*  1*  /
 F-3H  WATER  OPEN  RATE   3915.962  1*  1*  /
 F-4H  WATER  OPEN  RATE   1769.625  1*  1*  /
/

DATES
01 APR 2005 /
/

COMPDAT
 E-3CH  13  70  5  5  OPEN  1*   4.798  0.216   387.734  0  1*  Y  8.197  /
 E-3CH  13  69  5  5  OPEN  1*  31.679  0.216  2558.741  0  1*  Y  8.181  /
 E-3CH  13  68  5  5  OPEN  1*   7.111  0.216   571.629  0  1*  Y  8.014  /
 E-3CH  12  68  5  5  OPEN  1*   7.211  0.216   578.668  0  1*  Y  7.954  /
 E-3CH  11  64  5  5  OPEN  1*  17.745  0.216  1420.044  0  1*  Y  7.861  /
 E-3CH  11  63  5  5  OPEN  1*   1.181  0.216    94.262  0  1*  Y  7.776  /
 E-3CH  10  62  5  5  OPEN  1*   0.721  0.216    57.593  0  1*  Y  7.812  /
 E-3CH  10  61  5  5  OPEN  1*   4.384  0.216   350.687  0  1*  Y  7.848  /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  139.7458  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  184.5234  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  207.6555  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE  7320.434  1*  1*  /
 C-2H  WATER  OPEN  RATE  9055.350  1*  1*  /
 C-3H  WATER  OPEN  RATE  3463.965  1*  1*  /
 F-1H  WATER  OPEN  RATE  9477.715  1*  1*  /
 F-2H  WATER  OPEN  RATE  5830.365  1*  1*  /
 F-3H  WATER  OPEN  RATE  3493.896  1*  1*  /
 F-4H  WATER  OPEN  RATE  1557.130  1*  1*  /
/

DATES
24 APR 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  126.9300  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  185.3540  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  206.4369  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  190.2160  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE  7312.592  1*  1*  /
 C-2H  WATER  OPEN  RATE  9363.372  1*  1*  /
 C-3H  WATER  OPEN  RATE  3460.800  1*  1*  /
 F-1H  WATER  OPEN  RATE  9659.927  1*  1*  /
 F-2H  WATER  OPEN  RATE  5954.855  1*  1*  /
 F-3H  WATER  OPEN  RATE  3599.386  1*  1*  /
 F-4H  WATER  OPEN  RATE  1567.529  1*  1*  /
/

DATES
01 MAY 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  125.023  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  185.013  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  206.919  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*    1.013  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7276.440  1*  1*  /
 C-2H  WATER  OPEN  RATE   9196.154  1*  1*  /
 C-3H  WATER  OPEN  RATE   3681.797  1*  1*  /
 F-1H  WATER  OPEN  RATE  10097.600  1*  1*  /
 F-2H  WATER  OPEN  RATE   6422.041  1*  1*  /
 F-3H  WATER  OPEN  RATE   3871.919  1*  1*  /
 F-4H  WATER  OPEN  RATE   1335.639  1*  1*  /
/

DATES
01 JUN 2005 /
/

WCONPROD
  F-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  130.012  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  183.978  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  204.812  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE   7275.568  1*  1*  /
 C-2H  WATER  OPEN  RATE   9012.300  1*  1*  /
 C-3H  WATER  OPEN  RATE   3862.500  1*  1*  /
 F-1H  WATER  OPEN  RATE  10948.400  1*  1*  /
 F-2H  WATER  OPEN  RATE   6739.928  1*  1*  /
 F-3H  WATER  OPEN  RATE   4374.200  1*  1*  /
/

DATES
02 JUN 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  126.358  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  183.464  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  184.343  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  203.455  /
/

WCONINJE
 C-1H  WATER  OPEN  RATE  7233.464  1*  1*  /
 C-2H  WATER  OPEN  RATE  8664.992  1*  1*  /
 C-3H  WATER  OPEN  RATE  3573.208  1*  1*  /
 F-1H  WATER  OPEN  RATE  9992.871  1*  1*  /
 F-2H  WATER  OPEN  RATE  6429.187  1*  1*  /
 F-3H  WATER  OPEN  RATE  3838.846  1*  1*  /
 F-4H  WATER  OPEN  RATE  1043.858  1*  1*  /
/

DATES
26 JUN 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  153.432  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  184.529  /
 D-1CH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   901.00  1*  1*  /
  C-2H  WATER  OPEN  RATE  1044.96  1*  1*  /
  C-3H  WATER  OPEN  RATE   234.56  1*  1*  /
 C-4AH  WATER  OPEN  RATE  5319.24  1*  1*  /
  F-1H  WATER  OPEN  RATE  9089.24  1*  1*  /
  F-2H  WATER  OPEN  RATE  5256.02  1*  1*  /
  F-3H  WATER  OPEN  RATE  3248.82  1*  1*  /
  F-4H  WATER  OPEN  RATE  1317.50  1*  1*  /
/

DATES
01 JUL 2005 /
/

COMPDAT
 E-4AH  38  98  2  2  OPEN  1*  48.136  0.216  3456.518  0  1*  Y  5.061  /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  121.3787  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.7705  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  181.3023  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  213.4073  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7618.678  1*  1*  /
  C-2H  WATER  OPEN  RATE  7854.178  1*  1*  /
  C-3H  WATER  OPEN  RATE  3042.056  1*  1*  /
 C-4AH  WATER  OPEN  RATE  5182.311  1*  1*  /
  F-1H  WATER  OPEN  RATE  9912.400  1*  1*  /
  F-2H  WATER  OPEN  RATE  6300.109  1*  1*  /
  F-3H  WATER  OPEN  RATE  3713.622  1*  1*  /
  F-4H  WATER  OPEN  RATE  1687.109  1*  1*  /
/

DATES
10 JUL 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  125.5910  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.7109  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  179.5469  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  213.8630  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   3295.698  1*  1*  /
  C-2H  WATER  OPEN  RATE   2940.833  1*  1*  /
  C-3H  WATER  OPEN  RATE   1143.817  1*  1*  /
 C-4AH  WATER  OPEN  RATE   1922.115  1*  1*  /
  F-1H  WATER  OPEN  RATE  10510.900  1*  1*  /
  F-2H  WATER  OPEN  RATE   6675.806  1*  1*  /
  F-3H  WATER  OPEN  RATE   4024.667  1*  1*  /
  F-4H  WATER  OPEN  RATE   1834.733  1*  1*  /
/

DATES
16 JUL 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  141.9046  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.3054  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  182.1793  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  216.1103  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7666.687  1*  1*  /
  C-2H  WATER  OPEN  RATE   8191.408  1*  1*  /
  C-3H  WATER  OPEN  RATE   3199.100  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5317.152  1*  1*  /
  F-1H  WATER  OPEN  RATE  10604.600  1*  1*  /
  F-2H  WATER  OPEN  RATE   6444.666  1*  1*  /
  F-3H  WATER  OPEN  RATE   4213.931  1*  1*  /
  F-4H  WATER  OPEN  RATE    479.354  1*  1*  /
/

DATES
29 JUL 2005 /
/

WCONPROD
  F-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  137.569  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.797  /
 D-1CH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*   218.97  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7461.132  1*  1*  /
  C-2H  WATER  OPEN  RATE   8406.867  1*  1*  /
  C-3H  WATER  OPEN  RATE   3400.600  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5457.700  1*  1*  /
  F-1H  WATER  OPEN  RATE  10972.130  1*  1*  /
  F-2H  WATER  OPEN  RATE   6398.893  1*  1*  /
  F-3H  WATER  OPEN  RATE   4496.867  1*  1*  /
/

DATES
01 AUG 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  133.7122  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.3735  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  217.9566  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7394.7980  1*  1*  /
  C-2H  WATER  OPEN  RATE   6546.3500  1*  1*  /
  C-3H  WATER  OPEN  RATE   2389.1500  1*  1*  /
 C-4AH  WATER  OPEN  RATE   3959.6000  1*  1*  /
  F-1H  WATER  OPEN  RATE  11095.2500  1*  1*  /
  F-2H  WATER  OPEN  RATE   6369.9910  1*  1*  /
  F-3H  WATER  OPEN  RATE   4423.9000  1*  1*  /
  F-4H  WATER  OPEN  RATE    375.6499  1*  1*  /
/

DATES
03 AUG 2005 /
/

COMPDAT
 E-2AH  12  63  5  5  OPEN  1*   2.814  0.146   248.610  0  1*  Y  8.306  /
 E-2AH  12  62  5  5  OPEN  1*  16.504  0.146  1441.225  0  1*  Y  7.859  /
 E-2AH  12  61  5  5  OPEN  1*  17.389  0.146  1516.852  0  1*  Y  7.819  /
 E-2AH  12  60  5  5  OPEN  1*  17.893  0.146  1550.080  0  1*  Y  7.573  /
 E-2AH  12  59  5  5  OPEN  1*  18.674  0.146  1609.909  0  1*  Y  7.404  /
 E-2AH  12  58  5  5  OPEN  1*  19.772  0.146  1719.284  0  1*  Y  7.705  /
 E-2AH  12  57  5  5  OPEN  1*   5.345  0.146   470.937  0  1*  Y  8.192  /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  C-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 C-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  137.651  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.888  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  182.666  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  216.665  /
/

WCONINJE
 C-2H  WATER  OPEN  RATE     94.100  1*  1*  /
 F-1H  WATER  OPEN  RATE  10511.800  1*  1*  /
 F-2H  WATER  OPEN  RATE   6355.817  1*  1*  /
 F-3H  WATER  OPEN  RATE   4197.500  1*  1*  /
 F-4H  WATER  OPEN  RATE   1823.400  1*  1*  /
/

DATES
04 AUG 2005 /
/

COMPDAT
 D-3BH  15  48  7  7  OPEN  1*   2.300  0.216   178.019  0  1*  Y  6.825  /
 D-3BH  15  47  7  7  OPEN  1*  28.866  0.216  2240.595  0  1*  Y  6.911  /
 D-3BH  15  47  8  8  OPEN  1*  13.994  0.216  1091.152  0  1*  Y  7.042  /
 D-3BH  15  46  8  8  OPEN  1*  15.162  0.216  1200.026  0  1*  Y  7.500  /
 D-3BH  14  44  8  8  OPEN  1*  43.852  0.216  3421.184  0  1*  Y  7.058  /
 D-3BH  14  43  8  8  OPEN  1*  33.279  0.216  2613.848  0  1*  Y  7.261  /
 D-3BH  13  43  7  7  OPEN  1*  19.907  0.216  1528.747  0  1*  Y  6.611  /
 D-3BH  13  42  7  7  OPEN  1*  13.334  0.216  1029.724  0  1*  Y  6.766  /
 D-3BH  13  42  8  8  OPEN  1*  42.376  0.216  3278.559  0  1*  Y  6.817  /
 D-3BH  13  41  8  8  OPEN  1*  61.850  0.216  4789.974  0  1*  Y  6.846  /
 D-3BH  13  40  8  8  OPEN  1*   1.730  0.216   134.272  0  1*  Y  6.914  /
 D-3BH  12  40  8  8  OPEN  1*  63.807  0.216  4944.563  0  1*  Y  6.863  /
 D-3BH  12  39  8  8  OPEN  1*  12.763  0.216   988.058  0  1*  Y  6.835  /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  147.5762  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  180.8625  /
 D-1CH  OPEN  BHP  1*  1*  1*  1*  1*  184.8818  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  216.8892  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*  181.8332  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7395.586  1*  1*  /
  C-2H  WATER  OPEN  RATE   7081.532  1*  1*  /
  C-3H  WATER  OPEN  RATE   2654.032  1*  1*  /
 C-4AH  WATER  OPEN  RATE   4634.084  1*  1*  /
  F-1H  WATER  OPEN  RATE  10273.370  1*  1*  /
  F-2H  WATER  OPEN  RATE   6140.291  1*  1*  /
  F-3H  WATER  OPEN  RATE   4092.011  1*  1*  /
  F-4H  WATER  OPEN  RATE     18.443  1*  1*  /
/

DATES
01 SEP 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  134.634  /
  B-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-1CH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  220.524  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*    1.013  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7257.64500  1*  1*  /
  C-2H  WATER  OPEN  RATE  7354.76100  1*  1*  /
  C-3H  WATER  OPEN  RATE  2823.29200  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4813.64500  1*  1*  /
  F-1H  WATER  OPEN  RATE  9392.15600  1*  1*  /
  F-2H  WATER  OPEN  RATE  6105.72500  1*  1*  /
  F-3H  WATER  OPEN  RATE  3776.80000  1*  1*  /
  F-4H  WATER  OPEN  RATE    30.19199  1*  1*  /
/

DATES
14 SEP 2005 /
/

WCONPROD
  F-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  113.835  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.071  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  214.833  /
 E-2AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7198.287  1*  1*  /
  C-2H  WATER  OPEN  RATE  7271.212  1*  1*  /
  C-3H  WATER  OPEN  RATE  2900.359  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4741.104  1*  1*  /
  F-1H  WATER  OPEN  RATE  9302.582  1*  1*  /
  F-2H  WATER  OPEN  RATE  6105.336  1*  1*  /
  F-3H  WATER  OPEN  RATE  3809.029  1*  1*  /
/

DATES
01 OCT 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  123.4208  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.1192  /
 D-4AH  OPEN  BHP  1*  1*  1*  1*  1*  215.0045  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   7090.523  1*  1*  /
  C-2H  WATER  OPEN  RATE   8011.484  1*  1*  /
  C-3H  WATER  OPEN  RATE   3171.816  1*  1*  /
 C-4AH  WATER  OPEN  RATE   5200.272  1*  1*  /
  F-1H  WATER  OPEN  RATE  10408.090  1*  1*  /
  F-2H  WATER  OPEN  RATE   6108.194  1*  1*  /
  F-3H  WATER  OPEN  RATE   4077.429  1*  1*  /
/

DATES
01 NOV 2005 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  137.657  /
  B-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  5727.310  1*  1*  /
  C-2H  WATER  OPEN  RATE  6068.777  1*  1*  /
  C-3H  WATER  OPEN  RATE  2156.743  1*  1*  /
 C-4AH  WATER  OPEN  RATE  3304.541  1*  1*  /
  F-1H  WATER  OPEN  RATE  6777.863  1*  1*  /
  F-2H  WATER  OPEN  RATE  3992.133  1*  1*  /
  F-3H  WATER  OPEN  RATE  2518.350  1*  1*  /
/

DATES
01 DEC 2005 /
/

COMPDAT
 B-1AH  10  24  1  1  OPEN  1*  73.447  0.216  6088.146  0  1*  Y   9.166  /
 B-1AH  10  24  2  2  OPEN  1*  18.326  0.216  1563.065  0  1*  Y  10.423  /
 B-1AH   9  24  2  2  OPEN  1*  34.389  0.216  2922.668  0  1*  Y  10.256  /
 B-1AH   9  25  2  2  OPEN  1*  11.633  0.216   990.024  0  1*  Y  10.320  /
 B-1AH   9  25  3  3  OPEN  1*   6.676  0.216   540.569  0  1*  Y   8.269  /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  108.9759  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  168.1479  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7808.971  1*  1*  /
  C-2H  WATER  OPEN  RATE  7795.200  1*  1*  /
  C-3H  WATER  OPEN  RATE  2797.900  1*  1*  /
 C-4AH  WATER  OPEN  RATE  5074.000  1*  1*  /
  F-1H  WATER  OPEN  RATE  9827.600  1*  1*  /
  F-2H  WATER  OPEN  RATE  5115.130  1*  1*  /
  F-3H  WATER  OPEN  RATE  3581.200  1*  1*  /
/

DATES
02 DEC 2005 /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  126.1985  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.3419  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7062.328  1*  1*  /
  C-2H  WATER  OPEN  RATE  7705.604  1*  1*  /
  C-3H  WATER  OPEN  RATE  2734.993  1*  1*  /
 C-4AH  WATER  OPEN  RATE  3147.707  1*  1*  /
  F-1H  WATER  OPEN  RATE  8748.707  1*  1*  /
  F-2H  WATER  OPEN  RATE  5207.523  1*  1*  /
  F-3H  WATER  OPEN  RATE  3178.175  1*  1*  /
/

DATES
30 DEC 2005 /
/

COMPDAT
 B-1BH  8  26  13  13  OPEN  1*   498.936  0.216   42212.508  0  1*  Y  10.047  /
 B-1BH  8  27  13  13  OPEN  1*  1421.913  0.216  120431.148  0  1*  Y  10.096  /
 B-1BH  8  28  13  13  OPEN  1*  1463.870  0.216  125311.945  0  1*  Y  10.599  /
 B-1BH  8  29  13  13  OPEN  1*  1424.647  0.216  122987.359  0  1*  Y  11.018  /
 B-1BH  8  30  13  13  OPEN  1*   949.802  0.216   82308.109  0  1*  Y  11.215  /
 B-1BH  8  31  13  13  OPEN  1*  1537.515  0.216  134230.813  0  1*  Y  11.610  /
/

WCONPROD
 B-3H  OPEN  BHP  1*  1*  1*  1*  1*  129.4149  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.2780  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7046.123  1*  1*  /
  C-2H  WATER  OPEN  RATE  7351.850  1*  1*  /
  C-3H  WATER  OPEN  RATE  2646.600  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4778.100  1*  1*  /
  F-1H  WATER  OPEN  RATE  4114.000  1*  1*  /
  F-2H  WATER  OPEN  RATE  1008.200  1*  1*  /
  F-3H  WATER  OPEN  RATE  1180.950  1*  1*  /
/

DATES
01 JAN 2006 /
/

WCONPROD
 B-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 B-2H  OPEN  BHP  1*  1*  1*  1*  1*  187.947  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  6974.665  1*  1*  /
  C-2H  WATER  OPEN  RATE  6692.400  1*  1*  /
  C-3H  WATER  OPEN  RATE  2347.094  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4341.792  1*  1*  /
  F-1H  WATER  OPEN  RATE  9892.341  1*  1*  /
  F-2H  WATER  OPEN  RATE  6256.076  1*  1*  /
  F-3H  WATER  OPEN  RATE  3780.724  1*  1*  /
/

DATES
18 JAN 2006 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  173.388  /
  B-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*   88.552  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  6918.291  1*  1*  /
  C-2H  WATER  OPEN  RATE  7099.136  1*  1*  /
  C-3H  WATER  OPEN  RATE  2606.129  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4598.419  1*  1*  /
  F-1H  WATER  OPEN  RATE  9297.457  1*  1*  /
  F-2H  WATER  OPEN  RATE  5741.270  1*  1*  /
  F-3H  WATER  OPEN  RATE  3441.271  1*  1*  /
/

DATES
01 FEB 2006 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  154.9709  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  165.1349  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*    1.0130  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  6863.948  1*  1*  /
  C-2H  WATER  OPEN  RATE  6631.948  1*  1*  /
  C-3H  WATER  OPEN  RATE  2623.552  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4278.617  1*  1*  /
  F-1H  WATER  OPEN  RATE  6665.943  1*  1*  /
  F-2H  WATER  OPEN  RATE  3126.978  1*  1*  /
  F-3H  WATER  OPEN  RATE  2215.826  1*  1*  /
/

DATES
24 FEB 2006 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  172.865  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  169.888  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*  95.4501  /
/

WCONINJE
  C-2H  WATER  OPEN  RATE  6754.460  1*  1*  /
  C-3H  WATER  OPEN  RATE  2569.620  1*  1*  /
 C-4AH  WATER  OPEN  RATE  4373.358  1*  1*  /
  F-1H  WATER  OPEN  RATE  8151.460  1*  1*  /
  F-2H  WATER  OPEN  RATE  4814.838  1*  1*  /
  F-3H  WATER  OPEN  RATE  2999.960  1*  1*  /
/

DATES
01 MAR 2006 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  138.2691  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  159.5563  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*    1.0130  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  4648.416  1*  1*  /
  C-2H  WATER  OPEN  RATE  7295.768  1*  1*  /
  C-3H  WATER  OPEN  RATE  1308.536  1*  1*  /
 C-4AH  WATER  OPEN  RATE  3108.048  1*  1*  /
  F-1H  WATER  OPEN  RATE  9545.897  1*  1*  /
  F-2H  WATER  OPEN  RATE  3470.211  1*  1*  /
  F-3H  WATER  OPEN  RATE  6720.039  1*  1*  /
/

DATES
01 APR 2006 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  125.28060  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  159.73660  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  184.85490  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*   83.38411  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE  7064.379  1*  1*  /
  C-2H  WATER  OPEN  RATE  6155.354  1*  1*  /
  C-3H  WATER  OPEN  RATE     0.013  1*  1*  /
 C-4AH  WATER  OPEN  RATE  2225.487  1*  1*  /
  F-1H  WATER  OPEN  RATE  9345.092  1*  1*  /
  F-2H  WATER  OPEN  RATE  3501.100  1*  1*  /
  F-3H  WATER  OPEN  RATE  6755.579  1*  1*  /
  F-4H  WATER  OPEN  RATE     8.854  1*  1*  /
/

DATES
25 APR 2006 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  C-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  C-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 C-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*   118.51  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  157.366  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  181.856  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*  109.643  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  7336.234  1*  1*  /
 F-2H  WATER  OPEN  RATE  2421.698  1*  1*  /
 F-3H  WATER  OPEN  RATE  5301.000  1*  1*  /
 F-4H  WATER  OPEN  RATE  1703.550  1*  1*  /
/

DATES
01 MAY 2006 /
/

WCONPROD
  B-3H  OPEN  BHP  1*  1*  1*  1*  1*  134.6759  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  139.7268  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.1813  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*  174.0742  /
/

WCONINJE
  C-1H  WATER  OPEN  RATE   739.0418  1*  1*  /
  C-2H  WATER  OPEN  RATE   545.7060  1*  1*  /
  C-3H  WATER  OPEN  RATE     0.0290  1*  1*  /
 C-4AH  WATER  OPEN  RATE   107.6578  1*  1*  /
  F-1H  WATER  OPEN  RATE  8995.0060  1*  1*  /
  F-2H  WATER  OPEN  RATE  3433.2300  1*  1*  /
  F-3H  WATER  OPEN  RATE  6564.0450  1*  1*  /
  F-4H  WATER  OPEN  RATE  1760.3420  1*  1*  /
/

DATES
01 JUN 2006 /
/

WCONPROD
  C-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  C-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  C-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 C-4AH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  157.487  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  166.062  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-3CH  OPEN  BHP  1*  1*  1*  1*  1*    1.013  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8818.430  1*  1*  /
 F-2H  WATER  OPEN  RATE  3464.000  1*  1*  /
 F-3H  WATER  OPEN  RATE  6433.217  1*  1*  /
 F-4H  WATER  OPEN  RATE  1491.150  1*  1*  /
/

DATES
01 JUL 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  137.985  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  151.820  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  7966.771  1*  1*  /
 F-2H  WATER  OPEN  RATE  1776.826  1*  1*  /
 F-3H  WATER  OPEN  RATE  5629.781  1*  1*  /
 F-4H  WATER  OPEN  RATE  1822.577  1*  1*  /
/

DATES
01 AUG 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  143.5610  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  143.5769  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8875.114  1*  1*  /
 F-2H  WATER  OPEN  RATE  2579.957  1*  1*  /
 F-3H  WATER  OPEN  RATE  6637.750  1*  1*  /
 F-4H  WATER  OPEN  RATE  2170.164  1*  1*  /
/

DATES
15 AUG 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  155.5336  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  141.5722  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  175.2211  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8947.300  1*  1*  /
 F-2H  WATER  OPEN  RATE  3616.198  1*  1*  /
 F-3H  WATER  OPEN  RATE  6840.100  1*  1*  /
 F-4H  WATER  OPEN  RATE  2263.698  1*  1*  /
/

DATES
16 AUG 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  145.1833  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  140.7389  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.6082  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8152.125  1*  1*  /
 F-2H  WATER  OPEN  RATE  3084.867  1*  1*  /
 F-3H  WATER  OPEN  RATE  6461.906  1*  1*  /
 F-4H  WATER  OPEN  RATE  2129.992  1*  1*  /
/

DATES
01 SEP 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  147.9259  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  143.7919  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  172.4922  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  7850.231  1*  1*  /
 F-2H  WATER  OPEN  RATE  2665.454  1*  1*  /
 F-3H  WATER  OPEN  RATE  6154.854  1*  1*  /
 F-4H  WATER  OPEN  RATE  2026.213  1*  1*  /
/

DATES
14 SEP 2006 /
/

COMPDAT
 K-3H  11  24  5  5  OPEN  1*   64.799  0.216   4558.657  0  1*  Y  4.681  /
 K-3H  11  23  5  5  OPEN  1*   10.405  0.216    732.714  0  1*  Y  4.699  /
 K-3H  10  23  5  5  OPEN  1*  157.439  0.216  11212.515  0  1*  Y  4.904  /
 K-3H  10  22  5  5  OPEN  1*  143.999  0.216  10504.572  0  1*  Y  5.380  /
 K-3H  10  21  5  5  OPEN  1*   76.727  0.216   5566.416  0  1*  Y  5.266  /
 K-3H  11  21  5  5  OPEN  1*   55.811  0.216   4085.587  0  1*  Y  5.454  /
 K-3H  11  20  5  5  OPEN  1*  127.658  0.216   9149.834  0  1*  Y  5.025  /
 K-3H  11  19  5  5  OPEN  1*  126.628  0.216   9037.191  0  1*  Y  4.943  /
 K-3H  11  18  5  5  OPEN  1*  123.704  0.216   8854.442  0  1*  Y  4.999  /
 K-3H  11  17  5  5  OPEN  1*  119.860  0.216   8704.711  0  1*  Y  5.288  /
 K-3H  11  16  5  5  OPEN  1*    7.253  0.216    534.921  0  1*  Y  5.615  /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  164.3229  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  145.1936  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  176.6121  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8260.259  1*  1*  /
 F-2H  WATER  OPEN  RATE  2946.665  1*  1*  /
 F-3H  WATER  OPEN  RATE  6373.200  1*  1*  /
 F-4H  WATER  OPEN  RATE  2157.935  1*  1*  /
/

DATES
01 OCT 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  174.7469  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  144.8589  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  180.1100  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  8554.235  1*  1*  /
 F-2H  WATER  OPEN  RATE  3676.267  1*  1*  /
 F-3H  WATER  OPEN  RATE  6865.333  1*  1*  /
 F-4H  WATER  OPEN  RATE  2251.333  1*  1*  /
/

DATES
10 OCT 2006 /
/

WCONPROD
  F-4H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  146.768  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  179.198  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  9177.920  1*  1*  /
 F-2H  WATER  OPEN  RATE  3246.698  1*  1*  /
 F-3H  WATER  OPEN  RATE  7287.460  1*  1*  /
/

DATES
15 OCT 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  177.739  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  149.459  /
  D-2H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  190.722  /
 E-3CH  STOP  BHP  1*  1*  1*  1*  1*       1*  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  9166.412  1*  1*  /
 F-2H  WATER  OPEN  RATE  3913.071  1*  1*  /
 F-3H  WATER  OPEN  RATE  7378.047  1*  1*  /
/

DATES
01 NOV 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  175.035  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  154.961  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  183.874  /
  E-1H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*  176.455  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  10124.410  1*  1*  /
 F-2H  WATER  OPEN  RATE   3499.711  1*  1*  /
 F-3H  WATER  OPEN  RATE   7247.000  1*  1*  /
/

DATES
09 NOV 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  170.3930  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  152.2519  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  179.7259  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  187.8090  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*  127.0070  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  10695.200  1*  1*  /
 F-2H  WATER  OPEN  RATE   4304.548  1*  1*  /
 F-3H  WATER  OPEN  RATE   4118.750  1*  1*  /
/

DATES
11 NOV 2006 /
/

WCONPROD
  F-3H  STOP  BHP  1*  1*  1*  1*  1*       1*  /
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  168.739  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  152.016  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  178.091  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  180.319  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*  119.847  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  10179.93  1*  1*  /
 F-2H  WATER  OPEN  RATE   4378.95  1*  1*  /
/

DATES
17 NOV 2006 /
/

WCONPROD
  B-2H  OPEN  BHP  1*  1*  1*  1*  1*  179.2987  /
 D-3BH  OPEN  BHP  1*  1*  1*  1*  1*  147.6694  /
  D-2H  OPEN  BHP  1*  1*  1*  1*  1*  175.5245  /
  E-1H  OPEN  BHP  1*  1*  1*  1*  1*  189.6219  /
 E-2AH  OPEN  BHP  1*  1*  1*  1*  1*  171.2608  /
/

WCONINJE
 F-1H  WATER  OPEN  RATE  9662.379  1*  1*  /
 F-2H  WATER  OPEN  RATE  4574.643  1*  1*  /
/

DATES
01 DEC 2006 /
/
